name       : zanshin
version    : 22.04.3
release    : 16
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/zanshin-22.04.3.tar.xz : be38040659e48cffa09c738a36746364efefbbaf3b232cb05c0cf6b859e54dd9
license    :
    - GPL-3.0-or-alter
    - LGPL-2.1-only
component  : office.notes
summary    : To-do management application for KDE.
description: |
    A powerful yet simple application to manage your day to day actions.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Qml)
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - kcalendarcore-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcontacts-devel
    - kdeclarative-devel
    - kdelibs4support-devel
    - kidentitymanagement-devel
    - kldap-devel
    - kmbox-devel
    - kontactinterface-devel
    - kpimtextedit-devel
    - krunner-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
    - openldap-devel
rundeps    :
    - kded
    - kdepim-runtime
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
